#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - openjdk-17-jdk
  - wget
  - gnupg
  - curl

runcmd:
  - echo "Installing Jenkins..."
  - curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
  - echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" > /etc/apt/sources.list.d/jenkins.list
  - apt-get update
  - apt-get install -y jenkins
  - systemctl enable jenkins
  - systemctl start jenkins
