#cloud-config
package_update: true
packages:
  - openjdk-11-jre-headless

write_files:
  - path: /etc/systemd/system/jenkins-agent.service
    content: |
      [Unit]
      Description=Jenkins Agent
      After=network.target

      [Service]
      User=ubuntu
      WorkingDirectory=/opt/jenkins-agent
      ExecStart=/usr/bin/java -jar /opt/jenkins-agent/agent.jar -jnlpUrl http://http://13.212.206.203:8080/computer/agent1/jenkins-agent.jnlp -secret a037a2992783ae291709df9f38c352542bca9f754e6da4051e0ce434ba244d27 -workDir /opt/jenkins-agent
      Restart=always

      [Install]
      WantedBy=multi-user.target

runcmd:
  - mkdir -p /opt/jenkins-agent
  - curl -o /opt/jenkins-agent/agent.jar http://http://13.212.206.203:8080/jnlpJars/agent.jar
  - systemctl daemon-reload
  - systemctl enable jenkins-agent.service
  - systemctl start jenkins-agent.service
